### PR TITLE
Fix the NullPointerException bug in TopologyMetricRunnable ,when use …

### PR DESCRIPTION
**Pull request by L-Donne**
Fix the NullPointerException bug in TopologyMetricRunnable

### CODE REVIEW

**Comment by wuchong** [comment]
Can you describe the situation when bug occurs in detail?

**Comment by unsleepy22** [comment]
I'm ok with this PR, looks good.

**Comment by L-Donne** [comment]
isShutdown 初始值为null,由于本地模式起来的时候不会为isShutdown 重新赋值,在此后的逻辑里又没有区分本地模式和分布式模式，都会去调用 isShutdown.get() .所以在本地模式下就会出现空指针异常.

**Comment by wuchong** [comment]
+1

**Comment by unsleepy22** [comment]
merged, thanks~

**Pull request merged**
